### ISSUE TITLE
js error

### ISSUE THREAD

**Issue by staycanuca** [redmusicxd/iptv_ro#1]
hi I get this when I tr to access a channel:

`SyntaxError: Unexpected token } in JSON at position 95
    at JSON.parse (<anonymous>)
    at getLogin (C:\xxxxxxxxxxxx\antena.js:259:22)
    at C:\xxxxxxxxxxxxxxxxx\antena.js:133:24
    at new Promise (<anonymous>)
    at getShows (C:\xxxxxxxxxxxxxxxx\antena.js:131:10)
    at C:\xxxxxxxxxxxxxxxxxxxxxxxxxx\antena.js:66:24
    at new Promise (<anonymous>)
    at getShowsRoute (C:\xxxxxxxxxxxxxxxxxxxxxxxxxxxx\antena.js:64:10)
    at C:\xxxxxxxxxxxxxxxxxxxxxxxxxx\index.js:12:24
    at Layer.handle [as handle_request] (C:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\node_modules\express\lib\router\layer.js:95:5)`

**Comment by redmusicxd** [comment]
Could you please attach the auth.json content?

**Comment by redmusicxd** [comment]
Most probably you put an extra "}"

**Comment by staycanuca** [comment]
{
  "antena": {
    "username": "email",
    "password": "pass",
  },
  "digi": {
    "username": "",
    "password": "",
  },
  "pro": {
    "username": "email",
    "password": "pass",
  }
}

**Comment by redmusicxd** [comment]
ok, seems like it's my bad, accidentally put a comma after the password field
```json
{
"antena": {
"username": "email",
"password": "pass"
},
"digi": {
"username": "",
"password": ""
},
"pro": {
"username": "email",
"password": "pass"
}
}
```
this should be good.

**Comment by staycanuca** [comment]
login page is working great
